"""add business module tables

Revision ID: 779c2292f376
Revises: f9ab1f2fc68c
Create Date: 2026-08-25 09:14:31.940447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779c2292f376'
down_revision: Union[str, None] = 'f9ab1f2fc68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', name='business_verification_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=True)
    op.create_table('business_documents',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('REGISTRATION_CERTIFICATE', 'TAX_ID', 'BUSINESS_LICENSE', 'OTHER', name='business_document_type'), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='business_document_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_documents_business_profile_id'), 'business_documents', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_business_documents_status'), 'business_documents', ['status'], unique=False)
    op.create_table('business_rider_assignments',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('rider_profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='business_rider_assignment_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_profile_id'], ['rider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rider_assignments_business_profile_id'), 'business_rider_assignments', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_business_rider_assignments_rider_profile_id'), 'business_rider_assignments', ['rider_profile_id'], unique=False)
    op.create_index(op.f('ix_business_rider_assignments_status'), 'business_rider_assignments', ['status'], unique=False)
    op.create_index('ix_rider_assignments_one_active_per_rider', 'business_rider_assignments', ['rider_profile_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('fleets',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='business_fleet_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleets_business_profile_id'), 'fleets', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_fleets_fleet_code'), 'fleets', ['fleet_code'], unique=True)
    op.create_index(op.f('ix_fleets_status'), 'fleets', ['status'], unique=False)
    op.create_table('vehicles',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'RETIRED', name='business_vehicle_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_business_profile_id'), 'vehicles', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('fleet_vehicles',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='business_fleet_vehicle_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_vehicles_business_profile_id'), 'fleet_vehicles', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_fleet_vehicles_fleet_id'), 'fleet_vehicles', ['fleet_id'], unique=False)
    op.create_index('ix_fleet_vehicles_one_active_per_vehicle', 'fleet_vehicles', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_fleet_vehicles_status'), 'fleet_vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_fleet_vehicles_vehicle_id'), 'fleet_vehicles', ['vehicle_id'], unique=False)
    op.create_table('business_trips',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_id', sa.Uuid(), nullable=False),
    sa.Column('fleet_vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('rider_assignment_id', sa.Uuid(), nullable=False),
    sa.Column('rider_profile_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('revenue_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', 'CANCELLED', name='business_trip_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.ForeignKeyConstraint(['fleet_vehicle_id'], ['fleet_vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_assignment_id'], ['business_rider_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_profile_id'], ['rider_profiles.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_trips_business_profile_id'), 'business_trips', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_business_trips_fleet_id'), 'business_trips', ['fleet_id'], unique=False)
    op.create_index(op.f('ix_business_trips_fleet_vehicle_id'), 'business_trips', ['fleet_vehicle_id'], unique=False)
    op.create_index(op.f('ix_business_trips_rider_assignment_id'), 'business_trips', ['rider_assignment_id'], unique=False)
    op.create_index(op.f('ix_business_trips_rider_profile_id'), 'business_trips', ['rider_profile_id'], unique=False)
    op.create_index(op.f('ix_business_trips_status'), 'business_trips', ['status'], unique=False)
    op.create_index(op.f('ix_business_trips_vehicle_id'), 'business_trips', ['vehicle_id'], unique=False)
    op.create_table('business_revenue',
    sa.Column('business_profile_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recognized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['business_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_revenue_business_profile_id'), 'business_revenue', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_business_revenue_trip_id'), 'business_revenue', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_revenue_trip_id'), table_name='business_revenue')
    op.drop_index(op.f('ix_business_revenue_business_profile_id'), table_name='business_revenue')
    op.drop_table('business_revenue')
    op.drop_index(op.f('ix_business_trips_vehicle_id'), table_name='business_trips')
    op.drop_index(op.f('ix_business_trips_status'), table_name='business_trips')
    op.drop_index(op.f('ix_business_trips_rider_profile_id'), table_name='business_trips')
    op.drop_index(op.f('ix_business_trips_rider_assignment_id'), table_name='business_trips')
    op.drop_index(op.f('ix_business_trips_fleet_vehicle_id'), table_name='business_trips')
    op.drop_index(op.f('ix_business_trips_fleet_id'), table_name='business_trips')
    op.drop_index(op.f('ix_business_trips_business_profile_id'), table_name='business_trips')
    op.drop_table('business_trips')
    op.drop_index(op.f('ix_fleet_vehicles_vehicle_id'), table_name='fleet_vehicles')
    op.drop_index(op.f('ix_fleet_vehicles_status'), table_name='fleet_vehicles')
    op.drop_index('ix_fleet_vehicles_one_active_per_vehicle', table_name='fleet_vehicles', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_fleet_vehicles_fleet_id'), table_name='fleet_vehicles')
    op.drop_index(op.f('ix_fleet_vehicles_business_profile_id'), table_name='fleet_vehicles')
    op.drop_table('fleet_vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_business_profile_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_fleets_status'), table_name='fleets')
    op.drop_index(op.f('ix_fleets_fleet_code'), table_name='fleets')
    op.drop_index(op.f('ix_fleets_business_profile_id'), table_name='fleets')
    op.drop_table('fleets')
    op.drop_index('ix_rider_assignments_one_active_per_rider', table_name='business_rider_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_business_rider_assignments_status'), table_name='business_rider_assignments')
    op.drop_index(op.f('ix_business_rider_assignments_rider_profile_id'), table_name='business_rider_assignments')
    op.drop_index(op.f('ix_business_rider_assignments_business_profile_id'), table_name='business_rider_assignments')
    op.drop_table('business_rider_assignments')
    op.drop_index(op.f('ix_business_documents_status'), table_name='business_documents')
    op.drop_index(op.f('ix_business_documents_business_profile_id'), table_name='business_documents')
    op.drop_table('business_documents')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
