"""add investor module tables

Revision ID: 85710cde1193
Revises: 800151979240
Create Date: 2026-08-25 04:29:00.171105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85710cde1193'
down_revision: Union[str, None] = '800151979240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=150), nullable=False),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('kyc_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', name='investor_kyc_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_profiles_user_id'), 'investor_profiles', ['user_id'], unique=True)
    op.create_table('ev_assets',
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_monthly_return', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ALLOCATED', 'RETIRED', name='ev_asset_status'), nullable=False),
    sa.Column('owner_investor_profile_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_investor_profile_id'], ['investor_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ev_assets_asset_code'), 'ev_assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_ev_assets_owner_investor_profile_id'), 'ev_assets', ['owner_investor_profile_id'], unique=False)
    op.create_index(op.f('ix_ev_assets_status'), 'ev_assets', ['status'], unique=False)
    op.create_table('investor_kyc_documents',
    sa.Column('investor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('PAN', 'AADHAAR', 'PASSPORT', 'BANK_STATEMENT', 'OTHER', name='kyc_document_type'), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kyc_document_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_kyc_documents_investor_profile_id'), 'investor_kyc_documents', ['investor_profile_id'], unique=False)
    op.create_index(op.f('ix_investor_kyc_documents_status'), 'investor_kyc_documents', ['status'], unique=False)
    op.create_table('investor_transactions',
    sa.Column('investor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INVESTMENT', 'EARNING_CREDIT', 'PAYOUT', name='investor_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='investor_transaction_status'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_transactions_investor_profile_id'), 'investor_transactions', ['investor_profile_id'], unique=False)
    op.create_index(op.f('ix_investor_transactions_status'), 'investor_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_investor_transactions_type'), 'investor_transactions', ['type'], unique=False)
    op.create_table('payouts',
    sa.Column('investor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payout_status'), nullable=False),
    sa.Column('payout_method', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_investor_profile_id'), 'payouts', ['investor_profile_id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('investments',
    sa.Column('investor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('ev_asset_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='investment_status'), nullable=False),
    sa.Column('invested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ev_asset_id'], ['ev_assets.id'], ),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_ev_asset_id'), 'investments', ['ev_asset_id'], unique=False)
    op.create_index(op.f('ix_investments_investor_profile_id'), 'investments', ['investor_profile_id'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    op.create_table('investor_earnings',
    sa.Column('investor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACCRUED', 'PAID', name='earning_status'), nullable=False),
    sa.Column('paid_out_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investor_profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_out_id'], ['payouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_earnings_investment_id'), 'investor_earnings', ['investment_id'], unique=False)
    op.create_index(op.f('ix_investor_earnings_investor_profile_id'), 'investor_earnings', ['investor_profile_id'], unique=False)
    op.create_index(op.f('ix_investor_earnings_status'), 'investor_earnings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investor_earnings_status'), table_name='investor_earnings')
    op.drop_index(op.f('ix_investor_earnings_investor_profile_id'), table_name='investor_earnings')
    op.drop_index(op.f('ix_investor_earnings_investment_id'), table_name='investor_earnings')
    op.drop_table('investor_earnings')
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index(op.f('ix_investments_investor_profile_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_ev_asset_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_investor_profile_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_investor_transactions_type'), table_name='investor_transactions')
    op.drop_index(op.f('ix_investor_transactions_status'), table_name='investor_transactions')
    op.drop_index(op.f('ix_investor_transactions_investor_profile_id'), table_name='investor_transactions')
    op.drop_table('investor_transactions')
    op.drop_index(op.f('ix_investor_kyc_documents_status'), table_name='investor_kyc_documents')
    op.drop_index(op.f('ix_investor_kyc_documents_investor_profile_id'), table_name='investor_kyc_documents')
    op.drop_table('investor_kyc_documents')
    op.drop_index(op.f('ix_ev_assets_status'), table_name='ev_assets')
    op.drop_index(op.f('ix_ev_assets_owner_investor_profile_id'), table_name='ev_assets')
    op.drop_index(op.f('ix_ev_assets_asset_code'), table_name='ev_assets')
    op.drop_table('ev_assets')
    op.drop_index(op.f('ix_investor_profiles_user_id'), table_name='investor_profiles')
    op.drop_table('investor_profiles')
    # ### end Alembic commands ###
