"""cascade delete tokens with user

Revision ID: b20b436ec604
Revises: bb00a6acbe2b
Create Date: 2026-08-24 22:38:08.531108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20b436ec604'
down_revision: Union[str, None] = 'bb00a6acbe2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('verification_tokens_user_id_fkey', 'verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_tokens', type_='foreignkey')
    op.create_foreign_key('verification_tokens_user_id_fkey', 'verification_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
