"""add rider module tables

Revision ID: f9ab1f2fc68c
Revises: 85710cde1193
Create Date: 2026-08-25 05:10:44.864636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ab1f2fc68c'
down_revision: Union[str, None] = '85710cde1193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('driving_license_number', sa.String(length=30), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('kyc_status', sa.Enum('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED', name='rider_kyc_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_profiles_user_id'), 'rider_profiles', ['user_id'], unique=True)
    op.create_table('jobs',
    sa.Column('job_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('fare_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACCEPTED', 'COMPLETED', 'CANCELLED', name='rider_job_status'), nullable=False),
    sa.Column('assigned_rider_profile_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_rider_profile_id'], ['rider_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_assigned_rider_profile_id'), 'jobs', ['assigned_rider_profile_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_code'), 'jobs', ['job_code'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('rider_kyc_documents',
    sa.Column('rider_profile_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('DRIVING_LICENSE', 'AADHAAR', 'PAN', 'VEHICLE_INSURANCE', 'OTHER', name='rider_kyc_document_type'), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='rider_kyc_document_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rider_profile_id'], ['rider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_kyc_documents_rider_profile_id'), 'rider_kyc_documents', ['rider_profile_id'], unique=False)
    op.create_index(op.f('ix_rider_kyc_documents_status'), 'rider_kyc_documents', ['status'], unique=False)
    op.create_table('vehicle_bookings',
    sa.Column('rider_profile_id', sa.Uuid(), nullable=False),
    sa.Column('ev_asset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='rider_booking_status'), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ev_asset_id'], ['ev_assets.id'], ),
    sa.ForeignKeyConstraint(['rider_profile_id'], ['rider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_bookings_ev_asset_id'), 'vehicle_bookings', ['ev_asset_id'], unique=False)
    op.create_index(op.f('ix_vehicle_bookings_rider_profile_id'), 'vehicle_bookings', ['rider_profile_id'], unique=False)
    op.create_index(op.f('ix_vehicle_bookings_status'), 'vehicle_bookings', ['status'], unique=False)
    op.create_table('trips',
    sa.Column('rider_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_booking_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('fare_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', name='rider_trip_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_profile_id'], ['rider_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_booking_id'], ['vehicle_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_job_id'), 'trips', ['job_id'], unique=True)
    op.create_index(op.f('ix_trips_rider_profile_id'), 'trips', ['rider_profile_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_booking_id'), 'trips', ['vehicle_booking_id'], unique=False)
    op.create_table('rider_earnings',
    sa.Column('rider_profile_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACCRUED', 'PAID', name='rider_earning_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rider_profile_id'], ['rider_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_earnings_rider_profile_id'), 'rider_earnings', ['rider_profile_id'], unique=False)
    op.create_index(op.f('ix_rider_earnings_status'), 'rider_earnings', ['status'], unique=False)
    op.create_index(op.f('ix_rider_earnings_trip_id'), 'rider_earnings', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rider_earnings_trip_id'), table_name='rider_earnings')
    op.drop_index(op.f('ix_rider_earnings_status'), table_name='rider_earnings')
    op.drop_index(op.f('ix_rider_earnings_rider_profile_id'), table_name='rider_earnings')
    op.drop_table('rider_earnings')
    op.drop_index(op.f('ix_trips_vehicle_booking_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_rider_profile_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_job_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_vehicle_bookings_status'), table_name='vehicle_bookings')
    op.drop_index(op.f('ix_vehicle_bookings_rider_profile_id'), table_name='vehicle_bookings')
    op.drop_index(op.f('ix_vehicle_bookings_ev_asset_id'), table_name='vehicle_bookings')
    op.drop_table('vehicle_bookings')
    op.drop_index(op.f('ix_rider_kyc_documents_status'), table_name='rider_kyc_documents')
    op.drop_index(op.f('ix_rider_kyc_documents_rider_profile_id'), table_name='rider_kyc_documents')
    op.drop_table('rider_kyc_documents')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_code'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_assigned_rider_profile_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_rider_profiles_user_id'), table_name='rider_profiles')
    op.drop_table('rider_profiles')
    # ### end Alembic commands ###
