import { LegalPageLayout, LegalSection } from '@/components/shared/LegalPageLayout';

export const TermsOfService = () => {
  return (
    <LegalPageLayout eyebrow="Legal" title="Terms of Service" lastUpdated="21 July 2026">
      <LegalSection title="1. Acceptance of Terms">
        <p>
          These Terms of Service ("Terms") govern your access to and use of booklynkev.com and the
          services described on it (together, the "Service"), operated by Booklynk EV ("Booklynk
          EV", "we", "us", or "our"). By accessing the Service, submitting a lead capture form, or
          making an investment payment, you agree to be bound by these Terms.
        </p>
      </LegalSection>

      <LegalSection title="2. Description of Service">
        <p>
          Booklynk EV is a platform connecting three types of participants in India's EV economy:
        </p>
        <ul className="ml-5 list-disc space-y-2">
          <li>
            <span className="font-medium text-foreground">Investors</span>, who may purchase an EV
            asset for deployment into a managed fleet in exchange for a share of rental income;
          </li>
          <li>
            <span className="font-medium text-foreground">Riders</span>, who may access EVs for
            personal use or gig work; and
          </li>
          <li>
            <span className="font-medium text-foreground">Businesses</span>, who may partner with
            us to manage delivery or mobility fleets.
          </li>
        </ul>
        <p>
          Submitting a lead capture form or an investment payment through this website expresses
          interest in, or reserves a place in, one of these programs. It does not, by itself,
          constitute a complete legal agreement — participation in any program is subject to a
          separate agreement, which will be provided to you directly by our team before your
          arrangement becomes binding.
        </p>
      </LegalSection>

      <LegalSection title="3. Eligibility">
        <p>
          You must be at least 18 years old and capable of entering into a legally binding
          agreement under Indian law to use the Service, submit a lead, or make a payment.
        </p>
      </LegalSection>

      <LegalSection title="4. Investment Plans and Payments">
        <p>
          Investment plan pricing (Starter, Growth, Enterprise, and Custom Fleet) shown on the
          Service reflects current terms and is subject to change without prior notice. Investment
          amounts are determined and verified server-side at the time of payment — the amount you
          are actually charged is the amount confirmed at checkout, regardless of any figure
          displayed elsewhere on the Service.
        </p>
        <p>
          All payments are processed securely by Razorpay. We do not store your card, UPI, or
          banking details. A record of your payment is created and updated as it is processed, and
          you will receive confirmation once your payment is verified.
        </p>
      </LegalSection>

      <LegalSection title="5. No Guaranteed Returns — Investment Risk Disclaimer">
        <p>
          <strong className="text-foreground">
            Any return on investment (ROI), monthly rental income, or total-returns figure shown on
            the Service — including figures generated by the ROI calculator on the Investment Plans
            section — is an illustrative estimate only, calculated from a fixed monthly rental
            assumption. It is not a guarantee, projection, or promise of actual returns.
          </strong>{' '}
          Actual returns depend on factors including vehicle utilization, market conditions,
          maintenance, and fleet performance, and may be lower than estimated, or result in a loss.
          Past or projected performance is not indicative of future results. You should not rely
          solely on figures shown on this website when making an investment decision, and we
          encourage you to seek independent financial advice before investing.
        </p>
      </LegalSection>

      <LegalSection title="6. Cancellations and Refunds">
        <p>
          If you wish to cancel an investment before the associated agreement is signed, contact us
          as soon as possible using the details in Section 12. Refund eligibility and timelines for
          payments already processed by Razorpay will be governed by the specific investment
          agreement provided to you, and, where applicable, Razorpay's own payment processing
          terms. We aim to resolve cancellation requests promptly and in good faith.
        </p>
      </LegalSection>

      <LegalSection title="7. Rider and Business Partnerships">
        <p>
          Submitting your details as a prospective rider or business partner does not guarantee
          onboarding. Acceptance into a rider or business partnership program is subject to
          verification, eligibility criteria, and availability, and will be confirmed separately by
          our team.
        </p>
      </LegalSection>

      <LegalSection title="8. Intellectual Property">
        <p>
          All content on the Service — including text, graphics, logos, and the Booklynk EV name —
          is owned by or licensed to Booklynk EV and protected by applicable intellectual property
          laws. You may not reproduce, distribute, or create derivative works from this content
          without our prior written consent.
        </p>
      </LegalSection>

      <LegalSection title="9. Limitation of Liability">
        <p>
          To the fullest extent permitted by law, Booklynk EV shall not be liable for any indirect,
          incidental, special, or consequential damages arising out of or in connection with your
          use of the Service, including but not limited to loss of investment returns, loss of
          data, or business interruption, even if we have been advised of the possibility of such
          damages.
        </p>
      </LegalSection>

      <LegalSection title="10. Governing Law">
        <p>
          These Terms are governed by the laws of India, without regard to its conflict of law
          principles. Any disputes arising under these Terms shall be subject to the exclusive
          jurisdiction of the courts of India.
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to These Terms">
        <p>
          We may revise these Terms from time to time. We will post any changes on this page and
          update the "Last updated" date above. Continued use of the Service after changes become
          effective constitutes acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection title="12. Contact Us">
        <p>
          If you have questions about these Terms, contact us at{' '}
          <a href="mailto:support@booklynkev.com" className="text-primary hover:underline">
            support@booklynkev.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
};

export default TermsOfService;
